name: Publish Python 🐍 distribution to PyPI

on:
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This uses PyPI Trusted Publishing (no password needed)
          # See: https://docs.pypi.org/trusted-publishers/using-a-publisher/
          # You must set up PyPI project and link it to your repo first
          verbose: true
