name: Require PR Approval by Owner

on:
  pull_request:
    branches: [ main ]

jobs:
  require-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR approval
        uses: actions/github-script@v7
        with:
          script: |
            const owner = 'falatform';
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approved = reviews.data.some(r => r.user.login === owner && r.state === 'APPROVED');
            if (!approved) {
              core.setFailed(`PR must be approved by repository owner (${owner}).`);
            }
